import test from 'node:test';
import assert from 'node:assert/strict';
import {providerRequest,validateRequest} from './server.mjs';
const mission={id:'mission-4',kind:'intercept',role:'cutoff',assignedTick:30,reviewTick:90,waypoint:{x:20,z:30},targetId:'player',track:{position:{x:21,z:25},heading:.5,seenTick:28,ageSeconds:.1,uncertainty:3},reason:'Intercept last reported approach'};
const request=(observation)=>({version:1,sequence:1,tick:30,tanks:[{tankId:'enemy-1',role:'enemy',observation,candidates:[{id:'move-left',description:'Feasible left route toward assigned intercept'},{id:'cover',description:'Emergency cover with mission preserved'}]}]});
test('mission commander selects tactical nextaction, retains strategic assignment and treats fear/stalls safely',()=>{const observation={own:{shieldFraction:.12},mission,recentThreat:{kind:'damage'},remainingFlags:1,totalFlags:8};const before=structuredClone(observation);const payload=providerRequest(request(observation));const p=payload.questions.tank_0.instructions;assert.match(p,/must execute the assigned mission/);assert.match(p,/Do not choose a different strategy/);assert.match(p,/kind, role, waypoint and targetId/);assert.match(p,/until the squad commander changes it/);assert.match(p,/one finite life/);assert.match(p,/critical/);assert.match(p,/fire promptly/);assert.match(p,/motionFeedback/);assert.match(p,/feasible alternate/);assert.match(p,/never stubbornly chase the nearest flag/);assert.match(p,/dated/);assert.deepEqual(payload.state.observations,{'enemy-1':observation});assert.deepEqual(observation,before);assert.deepEqual(Object.keys(payload.questions.tank_0.criteria),['move-left','cover']);});
test('legacy and player commands retain their mission-compatible existing behavior',()=>{const legacy=providerRequest(request({own:{}})).questions.tank_0.instructions;assert.match(legacy,/STOP the opposing tank/);assert.doesNotMatch(legacy,/must execute the assigned mission/);const p=request({mission});p.tanks[0].role='player';assert.match(providerRequest(p).questions.tank_0.instructions,/Collect flags and survive/);assert.doesNotMatch(providerRequest(p).questions.tank_0.instructions,/must execute the assigned mission/);});
test('optional mission schema is bounded while old observations stay accepted',()=>{validateRequest(request({own:{}}));validateRequest(request({mission}));for(const malformed of [null,{...mission,kind:'invent'},{...mission,waypoint:{x:null,z:0}},{...mission,reason:'x'.repeat(513)},{...mission,track:{...mission.track,ageSeconds:-1}}])assert.throws(()=>validateRequest(request({mission:malformed})));});
test('mission track canonicalization preserves authorized dated reports without revealing another commander',()=>{const observation={mission:{...mission,track:{...mission.track,heading:7}},own:{heading:-1},contacts:[{id:'player',kind:'tank',source:'shared',seenTick:28,ageSeconds:.1,position:{x:21,z:25}}]};const before=structuredClone(observation);const copy=providerRequest(request(observation)).state.observations['enemy-1'];assert.deepEqual(Object.keys(copy),['mission','own','contacts']);assert.ok(copy.mission.track.heading>=0&&copy.mission.track.heading<2*Math.PI);assert.equal(copy.mission.track.seenTick,28);assert.equal(copy.contacts[0].source,'shared');assert.deepEqual(copy.mission.track.position,observation.mission.track.position);assert.deepEqual(observation,before);});
