import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {once} from 'node:events';
import {createJevServer,validateRequest,providerRequest} from './server.mjs';
import {RESERVATION_USD} from './budget.mjs';
const tank=(tankId=1,role='enemy')=>({tankId,role,observation:{visibleTargets:[],privateMarker:tankId},candidates:[{id:'hold',description:'Hold safe position'}]});
const body=(tanks=[tank()])=>({version:1,sequence:2,tick:30,tanks});
function success(){return new Response(JSON.stringify({answers:{tank_0:{type:'choice',choice:'hold',confidence:1,probabilities:{hold:1}}},usage:{input_tokens:100}}));}
async function fixture(options,fn){const dir=mkdtempSync(join(tmpdir(),'jev-http-'));const {server,budget,audit}=createJevServer({apiKey:'FAKE',ledgerFile:join(dir,'spend.json'),...options});server.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${server.address().port}`;try{await fn(url,budget,audit);}finally{server.close();server.closeAllConnections();await once(server,'close');rmSync(dir,{recursive:true,force:true});}}
const post=(url,b=body(),headers={})=>fetch(url+'/api/jev/decide',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(b)});
test('three enemies plus one player accepted, fifth or fourth enemy rejected',()=>{validateRequest(body([tank(1),tank(2),tank(3),tank(4,'player')]));assert.throws(()=>validateRequest(body([tank(1),tank(2),tank(3),tank(4)])));assert.throws(()=>validateRequest(body([tank(1),tank(2),tank(3),tank(4,'player'),tank(5)])));});
test('isolated commander perspectives, <=two upstream in flight, normalized decisions and spend',async()=>{let count=0,active=0,max=0;await fixture({fetchImpl:async(_url,opts)=>{count++;active++;max=Math.max(max,active);const p=JSON.parse(opts.body);assert.equal(Object.keys(p.state.observations).length,1);assert.match(p.questions.tank_0.instructions,/You command tank/);await new Promise(r=>setTimeout(r,10));active--;return success();}},async(url,budget)=>{const res=await post(url,body([tank(1),tank(2),tank(3),tank(4,'player')]));assert.equal(res.status,200);const r=await res.json();assert.equal(r.decisions.length,4);assert.equal(r.usage.inputTokens,400);assert.equal(count,4);assert.equal(max,2);assert.ok(Math.abs(budget.spentUsd-400*.042/1e6)<1e-12);});});
test('timeout conservatively charges reservation and budget blocks further paid requests',async()=>{let count=0;await fixture({timeoutMs:10,limitUsd:RESERVATION_USD,fetchImpl:async()=>{count++;return new Promise(()=>{});}},async(url,budget)=>{assert.equal((await post(url)).status,504);assert.equal(budget.spentUsd,RESERVATION_USD);assert.equal((await post(url)).status,402);assert.equal(count,1);});});
test('bad upstream choice/error retains max reservation; keys never sent to client',async()=>{await fixture({fetchImpl:async()=>new Response(JSON.stringify({answers:{},usage:{input_tokens:100}}))},async(url,budget)=>{const r=await post(url);assert.equal(r.status,502);assert.equal(budget.spentUsd,RESERVATION_USD);assert.ok(!(await r.text()).includes('FAKE'));});});
test('untrusted origins and oversized/fifth-tank requests never call provider',async()=>{let calls=0;await fixture({fetchImpl:async()=>{calls++;return success();}},async url=>{assert.equal((await post(url,body(),{Origin:'https://evil.example'})).status,403);assert.equal((await post(url,body([tank(1),tank(2),tank(3),tank(4),tank(5)]))).status,400);assert.equal(calls,0);const r=await fetch(url+'/health',{headers:{Origin:'http://localhost:5173'}});assert.equal(r.headers.get('access-control-allow-origin'),'http://localhost:5173');assert.equal((await r.json()).available,true);});});

import {buildCandidates} from '../src/jev/controller.ts';
test('actual frontend-built flag/engage/flank action IDs survive backend wire contract',async()=>{
 const observation={own:{id:'player-1',team:'player',position:{x:0,z:0},heading:0,speed:0,shieldFraction:1,ammo:100,fireReady:true,tick:30},contacts:[{id:'flag-3',kind:'flag',position:{x:0,z:25},seenTick:30},{id:'enemy-2',kind:'tank',team:'enemy',position:{x:10,z:30},seenTick:30}],memory:[],visited:[],geometry:[],bounds:160};
 const candidates=buildCandidates(observation).map(({id,description})=>({id,description}));
 assert.ok(candidates.some(c=>c.id==='flag:flag-3'));assert.ok(candidates.some(c=>c.id==='engage:enemy-2'));assert.ok(candidates.some(c=>c.id==='flank:enemy-2:-1'));
 await fixture({fetchImpl:async(_url,opts)=>{const p=JSON.parse(opts.body);const criteria=p.questions.tank_0.criteria;assert.ok(criteria['flag:flag-3']);return new Response(JSON.stringify({answers:{tank_0:{type:'choice',choice:'flag:flag-3',confidence:1,probabilities:Object.fromEntries(Object.keys(criteria).map(id=>[id,id==='flag:flag-3'?1:0]))}},usage:{input_tokens:100}}));}},async url=>{const res=await post(url,body([{tankId:'player-1',role:'player',observation,candidates}]));assert.equal(res.status,200);assert.equal((await res.json()).decisions[0].choice,'flag:flag-3');});
});
test('candidate IDs remain length bounded and reject unsafe punctuation',()=>{for(const actionId of ['x'.repeat(65),'flag:bad/key','flag:bad key','flag:bad"key']){const t=tank();t.candidates=[{id:actionId,description:'invalid'}];assert.throws(()=>validateRequest(body([t])));}});
test('all successful and failed calls are audited despite a partial batch failure; history paginated',async()=>{await fixture({fetchImpl:async(_url,opts)=>{const p=JSON.parse(opts.body);const tankId=Object.keys(p.state.observations)[0];if(tankId==='1')return new Response('oops',{status:500});await new Promise(r=>setTimeout(r,20));return success();}},async(url,budget,audit)=>{assert.equal((await post(url,body([tank(1),tank(2)]))).status,502);await new Promise(r=>setTimeout(r,40));assert.equal(audit.page(0,200).records.filter(r=>r.type==='request').length,2);assert.equal(audit.page(0,200).records.filter(r=>r.type==='result').length,1);assert.equal(audit.page(0,200).records.filter(r=>r.type==='error').length,1);assert.ok(audit.page(0,200).records.filter(r=>r.type==='request').every(r=>r.payload.questions.tank_0.instructions&&Object.keys(r.payload.state.observations).length===1));assert.ok(!JSON.stringify(audit.page(0,200).records).includes('FAKE'));const history=await (await fetch(url+'/api/jev/history?offset=0&limit=2')).json();assert.equal(history.records.length,2);assert.equal(history.nextOffset,2);assert.equal(history.total,4);const text=await(await fetch(url+'/api/jev/history/export')).text();assert.equal(text.trim().split('\n').length,4);});});
test('timeout logs exact request and conservative error charge',async()=>{await fixture({timeoutMs:10,fetchImpl:async()=>new Promise(()=>{})},async(url,budget,audit)=>{assert.equal((await post(url)).status,504);assert.equal(audit.page(0,200).records[0].type,'request');assert.equal(audit.page(0,200).records[1].type,'error');assert.equal(audit.page(0,200).records[1].costUsd,RESERVATION_USD);assert.equal(audit.page(0,200).records[0].callId,audit.page(0,200).records[1].callId);});});
test('audit append failure prevents every paid call and remains closed',async()=>{let calls=0;await fixture({fetchImpl:async()=>{calls++;return success();}},async(url,budget,audit)=>{audit.append=()=>{audit.healthy=false;throw new Error('disk failed');};assert.equal((await post(url)).status,503);assert.equal((await post(url)).status,503);assert.equal(calls,0);assert.equal(budget.spentUsd,0);});});
test('browser metadata audit is persisted and bounded without paid calls',async()=>{await fixture({},async(url,budget,audit)=>{const r=await fetch(url+'/api/jev/audit/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({browserSessionId:'session-1',sequence:1,tick:30,event:'applied',at:new Date().toISOString(),details:{tankId:'enemy-1',callId:'one'}})});assert.equal(r.status,200);assert.equal(audit.page(0,200).records[0].event,'applied');assert.equal(budget.spentUsd,0);});});
test('history callId filter selects only exact provider call and paginates selected records',async()=>{await fixture({fetchImpl:async()=>success()},async(url,budget,audit)=>{const a=await(await post(url,body([tank(1)]))).json();const b=await(await post(url,body([tank(2)]))).json();const callA=a.decisions[0].callId,callB=b.decisions[0].callId;assert.notEqual(callA,callB);const first=await(await fetch(url+`/api/jev/history?callId=${callA}&limit=1`)).json();assert.equal(first.total,2);assert.equal(first.nextOffset,1);assert.equal(first.records.length,1);assert.equal(first.records[0].callId,callA);assert.equal(first.records[0].type,'request');const second=await(await fetch(url+`/api/jev/history?callId=${callA}&offset=1&limit=1`)).json();assert.equal(second.records[0].type,'result');assert.equal(second.records[0].callId,callA);assert.equal(second.nextOffset,null);const missing=await(await fetch(url+'/api/jev/history?callId=00000000-0000-4000-8000-000000000000')).json();assert.deepEqual(missing,{records:[],nextOffset:null,total:0});assert.equal((await fetch(url+'/api/jev/history?callId=bad')).status,400);});});
test('enemy commander mission defends remaining flags with urgency, while survival and player mission remain intact',()=>{
 const enemy=tank('enemy-1');enemy.observation={own:{id:'enemy-1'},remainingFlags:2,totalFlags:8};const payload=providerRequest(body([enemy]));const prompt=payload.questions.tank_0.instructions;
 assert.match(prompt,/STOP the opposing tank from taking your flags/);assert.match(prompt,/remainingFlags/);assert.match(prompt,/totalFlags/);assert.match(prompt,/fewer flags remain/);assert.match(prompt,/interception and active flag defense/);assert.match(prompt,/patrol known flags or explore/);assert.match(prompt,/recent fire or low shields/);assert.match(prompt,/avoid suicidal charging/);assert.match(prompt,/peaceful regrouping or idling/);
 assert.deepEqual(payload.state.observations,{'enemy-1':enemy.observation});assert.match(prompt,/ONLY observations\["enemy-1"\]/);
 const playerPrompt=providerRequest(body([tank('player-1','player')])).questions.tank_0.instructions;assert.match(playerPrompt,/Collect flags and survive while fighting enemies\./);assert.doesNotMatch(playerPrompt,/STOP the opposing tank/);
});
test('bounded four-tank transport above32KiB is accepted, above64KiB and oversized individual provider payload are rejected',async()=>{
 let upstreamCalls=0;
 await fixture({fetchImpl:async(_url,opts)=>{upstreamCalls++;assert.ok(Buffer.byteLength(opts.body)<=32768);const p=JSON.parse(opts.body);assert.equal(Object.keys(p.state.observations).length,1);const ids=Object.keys(p.questions.tank_0.criteria);return new Response(JSON.stringify({answers:{tank_0:{type:'choice',choice:ids[0],confidence:1,probabilities:Object.fromEntries(ids.map((id,i)=>[id,i===0?1:0]))}},usage:{input_tokens:100}}));}},async url=>{
  const tanks=[tank(1),tank(2),tank(3),tank(4,'player')].map(t=>({...t,observation:{own:t.tankId,visibleGeometry:'x'.repeat(5000)},candidates:Array.from({length:16},(_,i)=>({id:'explore:'+i,description:'Safe observed route '+ 'x'.repeat(450)}))}));const batch=body(tanks);const bytes=Buffer.byteLength(JSON.stringify(batch));assert.ok(bytes>32768&&bytes<65536);assert.equal((await post(url,batch)).status,200);assert.equal(upstreamCalls,4);
  assert.equal((await post(url,{...batch,padding:'x'.repeat(65536)})).status,413);assert.equal(upstreamCalls,4);
  const oversized=tank(9);oversized.observation={visibleGeometry:'界'.repeat(5900)};oversized.candidates=Array.from({length:16},(_,i)=>({id:'explore:'+i,description:'界'.repeat(500)}));assert.ok(JSON.stringify(oversized.observation).length<6000);assert.ok(Buffer.byteLength(JSON.stringify(body([oversized])))<65536);assert.equal((await post(url,body([oversized]))).status,413);assert.equal(upstreamCalls,4);
 });
});
