const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d');
const duration=48;let time=0,playing=true,last=performance.now(),samples,actions,decisions;
const colors=['#ff756e','#ffbc61','#c8a2ff'];
const color=id=>id==='player'?'#5aefac':colors[Number(id.split('-').at(-1))%3]??'#f99';
const label=id=>id==='player'?'Player':`Enemy ${Number(id.split('-').at(-1))+1}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(name){const r=await fetch(`../2026-09-30/level5/${name}.json.gz`);if(!r.ok)throw Error(`Cannot load ${name}: ${r.status}`);return JSON.parse(await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).text());}
function indexAt(list,tick,getTick=x=>x.tick){let lo=0,hi=list.length;while(lo<hi){const m=(lo+hi)>>1;if(getTick(list[m])<=tick)lo=m+1;else hi=m;}return Math.max(0,lo-1);}
function frame(t){const tick=t*30,i=indexAt(samples,tick,x=>x.state.tick),a=samples[i].state,b=samples[Math.min(i+1,samples.length-1)].state,f=Math.max(0,Math.min(1,(tick-a.tick)/Math.max(1,b.tick-a.tick)));const interpolate=(tank,list)=>{const next=list.find(n=>n.id===tank.id);if(!next||next.alive!==tank.alive||next.lives!==tank.lives)return tank;let dh=(next.heading-tank.heading+Math.PI)%(Math.PI*2);if(dh<0)dh+=Math.PI*2;dh-=Math.PI;return {...tank,position:{x:tank.position.x+(next.position.x-tank.position.x)*f,z:tank.position.z+(next.position.z-tank.position.z)*f},heading:tank.heading+dh*f};};return {...a,players:a.players.map(t=>interpolate(t,b.players)),enemies:a.enemies.map(t=>interpolate(t,b.enemies)),tick};}
function viewAt(t){const s=frame(t),p=s.players[0];const group=[p,...s.enemies.filter(e=>e.alive&&Math.hypot(e.position.x-p.position.x,e.position.z-p.position.z)<65)];let xs=group.map(e=>e.position.x),zs=group.map(e=>e.position.z);return {x:(Math.min(...xs)+Math.max(...xs))/2,z:(Math.min(...zs)+Math.max(...zs))/2,span:Math.max(75,Math.max(...xs)-Math.min(...xs)+35,Math.max(...zs)-Math.min(...zs)+35)};}
// Centered temporal averaging keeps deterministic seek/render and avoids abrupt camera cuts.
function camera(t){const views=Array.from({length:17},(_,i)=>viewAt(Math.max(0,Math.min(duration,t+(i-8)*.15))));return {x:views.reduce((n,v)=>n+v.x,0)/17,z:views.reduce((n,v)=>n+v.z,0)/17,span:views.reduce((n,v)=>n+v.span,0)/17};}
function drawWorld(s,view,rect,inset=false){const scale=Math.min(rect.w,rect.h)/view.span;const xy=p=>({x:rect.x+rect.w/2+(p.x-view.x)*scale,y:rect.y+rect.h/2-(p.z-view.z)*scale});ctx.save();ctx.beginPath();ctx.rect(rect.x,rect.y,rect.w,rect.h);ctx.clip();ctx.fillStyle='#091723';ctx.fillRect(rect.x,rect.y,rect.w,rect.h);
ctx.strokeStyle='#173344';ctx.lineWidth=1;for(let i=-100;i<=100;i+=10){let a=xy({x:i,z:-100}),b=xy({x:i,z:100});ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();a=xy({x:-100,z:i});b=xy({x:100,z:i});ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
const corner=xy({x:-100,z:100});ctx.strokeStyle='#6e8594';ctx.strokeRect(corner.x,corner.y,200*scale,200*scale);
for(const o of s.obstacles){ctx.fillStyle='#e6bd52';if(o.kind==='wall'){const p=xy({x:o.min.x,z:o.max.z});ctx.fillRect(p.x,p.y,(o.max.x-o.min.x)*scale,(o.max.z-o.min.z)*scale);}else{const p=xy(o.position);ctx.beginPath();ctx.arc(p.x,p.y,o.pylonRadius*scale,0,7);ctx.fill();ctx.strokeStyle='#b89950';ctx.lineWidth=2;for(let k=0;k<2;k++){const h=o.bladeAngle+k*Math.PI/2;ctx.beginPath();ctx.moveTo(p.x-Math.sin(h)*o.bladeLength*scale,p.y+Math.cos(h)*o.bladeLength*scale);ctx.lineTo(p.x+Math.sin(h)*o.bladeLength*scale,p.y-Math.cos(h)*o.bladeLength*scale);ctx.stroke();}}}
for(const f of s.flags)if(!f.collected){const p=xy(f.position);ctx.fillStyle='#63d4ff';ctx.fillRect(p.x-1,p.y-7,2,13);ctx.beginPath();ctx.moveTo(p.x,p.y-7);ctx.lineTo(p.x+8,p.y-4);ctx.lineTo(p.x,p.y);ctx.fill();}
for(const item of s.pickups)if(!item.collected){const p=xy(item.position);ctx.fillStyle=item.kind==='shield'?'#67e9bd':'#afc1cb';ctx.fillRect(p.x-3,p.y-3,6,6);}
for(const tank of [...s.players,...s.enemies]){if(!tank.alive)continue;const p=xy(tank.position);if(!inset){const trail=samples.filter(v=>v.state.tick>s.tick-45&&v.state.tick<=s.tick);ctx.strokeStyle=color(tank.id)+'66';ctx.lineWidth=2;ctx.beginPath();let started=false;for(const v of trail){const tt=[...v.state.players,...v.state.enemies].find(e=>e.id===tank.id);if(!tt?.alive)continue;const q=xy(tt.position);if(!started){ctx.moveTo(q.x,q.y);started=true;}else ctx.lineTo(q.x,q.y);}ctx.stroke();}ctx.strokeStyle=color(tank.id);ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,inset?3:12,0,7);ctx.stroke();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(tank.heading);ctx.fillStyle=color(tank.id);ctx.beginPath();ctx.moveTo(0,-(inset?5:12));ctx.lineTo(inset?3:7,inset?4:7);ctx.lineTo(inset?-3:-7,inset?4:7);ctx.closePath();ctx.fill();ctx.restore();if(!inset){ctx.font='bold 13px system-ui';ctx.fillStyle=color(tank.id);ctx.fillText(label(tank.id),p.x+16,p.y-8);ctx.fillStyle='#34404a';ctx.fillRect(p.x-14,p.y+17,28,4);ctx.fillStyle=color(tank.id);ctx.fillRect(p.x-14,p.y+17,28*Math.max(0,tank.shield/tank.maxShield),4);}}
for(const shot of s.projectiles){const p=xy(shot.position);ctx.fillStyle='#fffbd2';ctx.beginPath();ctx.arc(p.x,p.y,inset?1.5:3,0,7);ctx.fill();}ctx.restore();}
function render(){const s=frame(time),view=camera(time);ctx.clearRect(0,0,canvas.width,canvas.height);drawWorld(s,view,{x:0,y:0,w:1030,h:750});drawWorld(s,{x:0,z:0,span:215},{x:795,y:12,w:220,h:220},true);ctx.strokeStyle='#90a9b9';ctx.strokeRect(795,12,220,220);ctx.fillStyle='#dce8ee';ctx.font='13px system-ui';ctx.fillText('FULL ARENA · +z up / +x right',805,247);
document.querySelector('#time').textContent=`${time.toFixed(1)}s / 48.0s`;
document.querySelector('#score').textContent=`Flags ${s.flagsCollected}/${s.flags.length} · Lives ${s.players[0].lives} · Score ${s.score}`;
const latest=decisions.slice(0,indexAt(decisions,s.tick)+1).filter(d=>d.tick<=s.tick);document.querySelector('#cards').innerHTML=[...s.players,...s.enemies].map(t=>{const list=actions.get(t.id)??[],a=list[indexAt(list,s.tick)];const d=latest.findLast(d=>d.request?.tanks.some(q=>q.tankId===t.id)),req=d?.request.tanks.find(q=>q.tankId===t.id);const contact=(req?.observation.contacts??[]).filter(c=>c.kind==='tank'&&c.team!==req.observation.own.team);const dec=d?.decisions?.find(x=>x.tankId===t.id);return `<article style="border-color:${color(t.id)}"><b>${label(t.id)} · ${esc(req?.observation.own.personality??'player')}</b><p>${t.alive?'Shield '+t.shield+'/'+t.maxShield:'Destroyed / respawning'}</p><div class="action">${esc(a?.planId??'Local fallback')}</div><p>Strategy: ${esc(a?.strategy??'fallback')} · ${a?.command.fire?'Firing':'Not firing'}</p><details><summary>Decision context</summary><p>${esc(dec?.choice===a?.planId?dec.description:'')}</p></details><p>Last request ${((d?.tick??0)/30).toFixed(1)}s: ${contact.length?contact.map(c=>esc(c.id)+' / '+esc(c.source)+' / age '+(c.ageSeconds??0).toFixed(1)+'s').join('; '):'no opposing tanks reported'}</p></article>`;}).join('');document.querySelector('#seek').value=time;}
window.__replay={ready:false,duration,setTime(t){playing=false;time=Math.max(0,Math.min(duration,t));render();}};
try{[samples,actions,decisions]=await Promise.all(['samples','actions','decisions'].map(load));samples.sort((a,b)=>a.state.tick-b.state.tick);decisions.sort((a,b)=>a.tick-b.tick);const grouped=new Map();for(const a of actions){if(!grouped.has(a.id))grouped.set(a.id,[]);grouped.get(a.id).push(a);}for(const v of grouped.values())v.sort((a,b)=>a.tick-b.tick);actions=grouped;window.__replay.ready=true;render();requestAnimationFrame(function loop(now){if(playing){time=Math.min(duration,time+(now-last)/1000*Number(document.querySelector('#speed').value));if(time===duration)playing=false;}last=now;render();requestAnimationFrame(loop);});}catch(e){document.querySelector('#error').textContent=e.message;}
document.querySelector('#play').onclick=()=>{playing=!playing;document.querySelector('#play').textContent=playing?'Pause':'Play';};document.querySelector('#seek').oninput=e=>window.__replay.setTime(Number(e.target.value));
