import assert from 'node:assert/strict';
import { createInitialState } from '../../src/sim/simulation.ts';
import { observeTank } from '../../src/jev/observation.ts';
import { buildCandidates, commandForPlan } from '../../src/jev/controller.ts';
const state=createInitialState(5,[{loadout:{speed:10,shields:100,ammo:100}}]);
state.obstacles=[];state.flags=[];state.pickups=[];
const enemy=state.enemies[0]!;state.enemies=[enemy];enemy.position={x:0,z:0};enemy.prevPosition={...enemy.position};enemy.heading=0;enemy.speed=0;
state.players[0]!.position={x:90,z:90};
const observation=observeTank(state,enemy.id,{seen:{}});
observation.contacts=[{id:'player',kind:'tank',team:'player',position:{x:20,z:30},source:'shared',seenTick:state.tick,ageSeconds:0}];
let plans=buildCandidates(observation);
assert(!plans.some(p=>p.id==='hold:player'),'shared-only report must not offer idle blind hold');
assert(plans.some(p=>p.targetId==='player'&&Math.hypot(p.waypoint.x,p.waypoint.z)>3),'shared report offers purposeful movement');
assert(plans.filter(p=>p.targetId==='player').every(p=>!p.description.includes('visible target')),'spotter description must not imply own visibility');
state.players[0]!.position={x:20,z:30};
const own=observeTank(state,enemy.id,{seen:{}});
plans=buildCandidates(own);
const hold=plans.find(p=>p.id==='hold:player')!;
assert(hold,'own visible target allows hold');assert.deepEqual(hold.lookAt,{x:20,z:30});
state.players[0]!.position={x:90,z:90};
const command=commandForPlan(state,enemy.id,hold);
assert.equal(command.turn,1,'lost LOS faces last observed position, not zero-vector north');
assert.equal(command.fire,false,'lost own LOS never fires blindly');
assert.deepEqual(hold.lookAt,{x:20,z:30},'hidden target movement does not update lookAt');
console.log('Shared-only combat movement, own hold and lost-LOS last-heading tests passed');
