import assert from 'node:assert/strict';
import { JevSession } from '../src/game/jev-session.ts';
import { createInitialState } from '../src/sim/simulation.ts';
import { DEFAULT_LOADOUT } from '../src/config/constants.ts';
const state=()=>createInitialState(1,[{loadout:DEFAULT_LOADOUT}],'solo');
const flush=()=>new Promise(r=>setTimeout(r,0));
let sent:unknown;
const mock=(async(_url:unknown,init:RequestInit)=>{const req=JSON.parse(String(init.body));sent=req;return new Response(JSON.stringify({sequence:req.sequence,tick:req.tick,decisions:req.tanks.map((t:{tankId:string;candidates:{id:string}[]})=>({tankId:t.tankId,choice:t.candidates[0]!.id}))}));}) as typeof fetch;
const s=state(),j=new JevSession(mock);j.configure({enabled:true,playerAutopilot:true});j.update(s,0,true,true,true);await flush();
assert.deepEqual(j.getDecisionLog()[0]!.request,sent,'records exact attempted browser input');
assert.equal(j.getDecisionLog()[0]!.outcome,'accepted');assert.ok(j.getDecisionLog()[0]!.response);
assert.equal(j.getDecisionLog()[0]!.decisions[0]!.applied,false);j.commands(s,true);assert.ok(j.getDecisionLog()[0]!.decisions.every(d=>d.applied));
assert.equal((await j.exportDecisionLog())[0]!.decisions[0]!.applied,true,'durable export updated when executed');
const failed=new JevSession((async()=>{throw new Error('network failed');}) as typeof fetch);failed.configure({enabled:true});failed.update(state(),0,true,true,true);await flush();assert.equal(failed.getDecisionLog()[0]!.outcome,'failed');
let resolve!:(value:Response)=>void;const delayed=new JevSession((async()=>new Promise<Response>(r=>resolve=r)) as typeof fetch);const ds=state();delayed.configure({enabled:true});delayed.update(ds,0,true,true,true);delayed.update(ds,50,false,true,true);assert.equal(delayed.getDecisionLog()[0]!.outcome,'canceled');resolve(new Response('{}'));await flush();assert.equal(delayed.getDecisionLog()[0]!.outcome,'canceled');
for(let i=1;i<105;i++){j.update(s,i*1000,true,true,true);await flush();}assert.equal(j.getDecisionLog().length,100);assert.equal((await j.exportDecisionLog()).length,105,'live window bounded while full attempts retained');
console.log('Exact request/response, accepted vs executed, failed/canceled attempts and durable full export pass.');
const squadState=createInitialState(5,[{loadout:DEFAULT_LOADOUT}],'solo');squadState.obstacles=[];squadState.enemies.splice(3);squadState.players[0]!.position={x:0,z:0};
squadState.enemies[0]!.position={x:0,z:-20};squadState.enemies[0]!.heading=0;
squadState.enemies[1]!.position={x:-80,z:0};squadState.enemies[1]!.heading=0;
squadState.enemies[2]!.position={x:0,z:80};squadState.enemies[2]!.heading=0;
const squad=new JevSession(mock);squad.configure({enabled:true,playerAutopilot:true});squad.update(squadState,0,true,true,true);await flush();
const shared=squad.getObservation(squadState.enemies[1]!.id)!;assert.ok(shared.contacts.some(c=>c.id==='player'&&c.source==='shared'),'outside-own-range commander receives actual ally report at level5');
assert.ok(!squad.getObservation('player')!.contacts.some(c=>c.id==='player'),'enemy player reports never enter player commander contacts');
squad.update(squadState,1000,true,true,true);await flush();assert.equal(squad.getObservation(squadState.enemies[0]!.id)!.own.lastStrategy,squad.getStats().latestStrategies[squadState.enemies[0]!.id]);
console.log('Level5 actual ally reports and accepted prior strategy context pass.');
const playerIntel=squad.getObservation('player')!;const enemyIntel=playerIntel.contacts.filter(c=>c.kind==='tank'&&c.team==='enemy');
assert.ok(enemyIntel.length>0);assert.ok(enemyIntel.every(c=>c.strategy===squad.getStats().latestStrategies[c.id]),'tier5 player testing commander receives each AI enemy last accepted strategy');
