import assert from 'node:assert/strict';
import { JevSession } from '../src/game/jev-session.ts';
import { createInitialState } from '../src/sim/simulation.ts';
import { DEFAULT_LOADOUT } from '../src/config/constants.ts';

const makeState = () => createInitialState(1, [{loadout:DEFAULT_LOADOUT}], 'solo');
const flush = () => new Promise(resolve => setTimeout(resolve, 0));
let requests: unknown[] = [];
const mock = (async (_url: unknown, init: RequestInit) => {
  const body = JSON.parse(String(init.body)); requests.push(body);
  return new Response(JSON.stringify({sequence:body.sequence,tick:body.tick,decisions:body.tanks.map((tank: {tankId:string;candidates:{id:string}[]}) => ({tankId:tank.tankId,choice:tank.candidates[0]!.id})),usage:{inputTokens:123},spentUsd:0.001}));
}) as typeof fetch;
const state = makeState(), jev = new JevSession(mock);
jev.update(state,0,true,true,true); await flush(); assert.equal(requests.length,0,'disabled sends no requests');
jev.configure({enabled:true,playerAutopilot:true,hz:5});
jev.update(state,0,true,true,true); await flush();
assert.equal(requests.length,1); assert.ok(jev.getStats().modelDecisions>0);
jev.commands(state,true);
const appliedOnce=Object.values(jev.getStats().appliedChoiceHistogram).reduce((sum,e)=>sum+e.count,0);
assert.ok(appliedOnce>0,'accepted choices histogram records first applied command');
jev.commands(state,true);
assert.equal(Object.values(jev.getStats().appliedChoiceHistogram).reduce((sum,e)=>sum+e.count,0),appliedOnce,'histogram does not count repeated command ticks as new decisions');
assert.ok(Object.keys(jev.getStats().latestPlans).length>0);
assert.ok(jev.getStats().latencySamplesMs.length>0);
jev.update(state,100,true,true,true); await flush(); assert.equal(requests.length,1,'5 Hz cadence');
jev.update(state,200,true,true,true); await flush(); assert.equal(requests.length,2);
jev.update(state,400,false,true,true); await flush(); assert.equal(requests.length,2,'paused no requests');
jev.update(state,600,true,true,false); await flush(); assert.equal(requests.length,2,'background no requests');
jev.update(state,800,true,false,true); await flush(); assert.equal(requests.length,2,'net no requests');
state.mode='coop'; jev.update(state,1000,true,true,true); await flush(); assert.equal(requests.length,2,'coop no requests');
state.mode='solo'; state.enemies.push(...makeState().enemies,...makeState().enemies); jev.enforceRoster(state); assert.ok(state.enemies.length<=3);
const offline = new JevSession((async()=> {throw new Error('offline');}) as typeof fetch);
offline.configure({enabled:true}); offline.update(state,0,true,true,true); await flush(); assert.equal(offline.getStats().failures,1); assert.match(offline.getStats().status,/Offline fallback/); assert.ok(offline.commands(state,true));
let finish: (r:Response)=>void = ()=>{};
const delayed = new JevSession((async()=>await new Promise<Response>(r=>{finish=r;})) as typeof fetch);
delayed.configure({enabled:true}); delayed.update(state,0,true,true,true);
state.tick+=100; finish(new Response(JSON.stringify({sequence:1,tick:0,decisions:[]}))); await flush(); assert.equal(delayed.getStats().staleResponses,1);
console.log('Jev scheduler tests passed: disabled, cadence, pause, hidden, network, coop, cap, offline, stale.');

// Physical contacts are emitted on resolved penetration, never on a mere near miss.
const { step } = await import('../src/sim/simulation.ts');
const { updateProjectiles } = await import('../src/sim/weapons.ts');
const physics = makeState(); physics.obstacles=[];
const enemy = physics.enemies[0]!;
enemy.position={...physics.players[0]!.position};
step(physics, {});
assert.ok(physics.events.some(e=>e.type==='TankContact' && e.penetration>0));
const ally = physics.enemies[1]!;
ally.position={x:20,z:20}; enemy.position={x:20,z:10};
physics.projectiles=[{id:'test-shot',ownerId:enemy.id,position:{x:20,z:19.5},prevPosition:{x:20,z:19.5},heading:0,speed:30,ticksRemaining:10}];
const events: import('../src/sim/events.ts').SimEvent[]=[];
updateProjectiles(physics,events);
assert.ok(events.some(e=>e.type==='FriendlyFireHit' && e.damage>0));
console.log('Physical telemetry tests passed: resolved tank penetration and actual friendly projectile damage.');

const combat = makeState(); combat.god=false; combat.obstacles=[];
const victim=combat.players[0]!; victim.invulnerableTicks=0; victim.position={x:20,z:20};
const shooter=combat.enemies[0]!; shooter.position={x:20,z:10};
combat.projectiles=[{id:'damage-test',ownerId:shooter.id,position:{x:20,z:19.5},prevPosition:{x:20,z:19.5},heading:0,speed:30,ticksRemaining:10}];
const damageEvents: import('../src/sim/events.ts').SimEvent[]=[];
const beforeShield=victim.shield;updateProjectiles(combat,damageEvents);combat.events=damageEvents;
const damageTracker=new JevSession(mock);damageTracker.configure({enabled:true});damageTracker.recordTick(combat);
assert.equal(damageTracker.getStats().playerDamage,beforeShield-victim.shield,'actual enemy projectile damage authoritative');

const privacyState=makeState(), privacy=new JevSession(mock);privacy.configure({enabled:true,playerAutopilot:true});privacy.update(privacyState,performance.now(),true,true,true);await flush();
const playerObservation=privacy.getObservation('player');assert.ok(playerObservation);
privacyState.events=[{type:'EnemyRespawned',enemyId:privacyState.enemies[0]!.id,position:{x:50,z:50}}];privacy.recordTick(privacyState);
assert.deepEqual(privacy.getObservation('player'),playerObservation,'enemy respawn preserves unrelated commander observation/memory');
assert.equal(privacy.getObservation(privacyState.enemies[0]!.id),null,'respawn resets only own observation');
console.log('Authoritative damage, applied-choice histogram, and commander lifecycle privacy tests pass.');
const timingState=makeState(), timing=new JevSession(mock);timing.configure({enabled:true});const base=performance.now();
timing.update(timingState,base,true,true,true);await flush();
timingState.enemies[0]!.alive=false;timing.update(timingState,base+1000,true,true,true);await flush();
timing.update(timingState,base+2000,false,true,true);
assert.ok(Math.abs(timing.getStats().activeSeconds-2)<1e-9);
assert.ok(Math.abs(timing.getStats().activeTankSeconds.enemy-3)<1e-9,'denominator integrates living commanders, not stale observation count');
assert.equal(timing.getStats().activeTankSeconds.player,0);
let exhaustedRequests=0;
const exhausted=new JevSession((async()=>{exhaustedRequests++;return new Response(JSON.stringify({spentUsd:9.9,error:'Budget exhausted'}),{status:402});}) as typeof fetch);
exhausted.configure({enabled:true});const budgetState=makeState();exhausted.update(budgetState,0,true,true,true);await flush();exhausted.update(budgetState,1000,true,true,true);await flush();
assert.equal(exhaustedRequests,1,'402 stops further paid requests');
assert.equal(exhausted.getStats().spentUsd,9.9);assert.equal(exhausted.getStats().budgetExhausted,true);assert.match(exhausted.getStats().status,/Budget exhausted/);assert.ok(exhausted.commands(budgetState,true),'offline guards remain enabled');
exhausted.configure({enabled:false});exhausted.configure({enabled:true});exhausted.update(budgetState,2000,true,true,true);await flush();assert.equal(exhaustedRequests,1,'checkbox toggle cannot restart paid requests after exhaustion');
const malformed=new JevSession((async()=>new Response('bad-json',{status:402})) as typeof fetch);malformed.configure({enabled:true});malformed.update(makeState(),0,true,true,true);await flush();assert.equal(malformed.getStats().budgetExhausted,true,'malformed budget JSON still stops');
const diagnosticsState=makeState(), diagnostics=new JevSession(mock);diagnostics.configure({enabled:true,playerAutopilot:true});diagnostics.update(diagnosticsState,performance.now(),true,true,true);await flush();
const diagnosticTank=diagnosticsState.enemies[0]!;
for(let i=0;i<40;i++){diagnosticsState.tick=i+1;diagnosticsState.events=[{type:'ObstacleContact',tankId:diagnosticTank.id,obstacleId:'test-wall',penetration:.1}];diagnostics.recordTick(diagnosticsState);}
const safety=diagnostics.getStats().lastSafetyEvents;assert.equal(safety.length,32);assert.equal(safety[0]!.tick,8);assert.equal(safety[31]!.tick,39);assert.equal(safety[31]!.tanks[0]!.id,diagnosticTank.id);assert.ok(safety[31]!.tanks[0]!.planId);assert.equal(safety[31]!.tanks[0]!.modelAgeTicks,39);
const savedX=safety[31]!.tanks[0]!.position.x;diagnosticTank.position.x+=10;assert.equal(diagnostics.getStats().lastSafetyEvents[31]!.tanks[0]!.position.x,savedX,'diagnostic pose frozen at physical event');
console.log('Budget402 hard browser stop and bounded safety snapshot tests pass.');
